services:
  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: game
      POSTGRES_PASSWORD: gamepass
      POSTGRES_DB: game_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  godot-server:
    build:
      context: ./godot-server
    image: godot-server:latest
    platform: linux/amd64

volumes:
  postgres_data: